---
language: perl
perl:
  - '5.12'
  - '5.14'
  - '5.18'
  - '5.20'
notifications:
  email: false
install:
  - cpanm --notest Dist::Zilla
  - dzil listdeps |cpanm --notest
  - cpanm --notest -q --mirror-only --installdeps .
script:
  - prove -r t
